#Drone CI File!
#Commit Message: Drone! Captain Canary is here! 

kind: pipeline
type: kubernetes
name: default 
steps:
- name: build
  image: golang:1.13
  commands:
    - "go build -o ./myapp"
trigger:
  branch:
  - master

- name: publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nikpap/myfirstdrone
    auto_tag: true
    auto_tag_suffix: drone-build
    
 
- name: harness-deploy
  image: rlachhman/drone-harness-trigger:1.0.0
  settings:  
    accountid:
      from_secret: harness_accountid
    apikey: 
      from_secret: harness_apikey
    applicationid: 
      from_secret: harness_applicationid
    harnesswebhookid: 
      from_secret: harness_webhookid
    harnessartifactname: "harness_todolist-sample"
    artifactversion: "81"
    harnessservicename: "order-service"
